class ExpenseCategories {
  static const Map<String, List<String>> categories = {
    'Food & Dining': [
      'Restaurant',
      'Fast Food',
      'Street Food',
      'Cafe/Coffee',
      'Bar/Pub',
      'Alcohol',
      'Groceries',
      'Snacks',
      'Breakfast',
      'Lunch',
      'Dinner',
      'Room Service',
      'Delivery',
      'Other',
    ],
    'Transportation': [
      'Flights',
      'Trains',
      'Buses',
      'Taxis/Ride Share/Bolt/Grab',
      'Car Rental',
      'Fuel/Gas',
      'Parking',
      'Tolls',
      'Metro/Subway',
      'Ferry/Boat',
      'Airport Transfer',
      'Local Transport',
      'Bike Rental',
      'Scooter Rental',
      'Other',
    ],
    'Accommodation': [
      'Hotel',
      'Hostel',
      'Airbnb',
      'Resort',
      'Camping',
      'Guesthouse',
      'Apartment Rental',
      'Villa',
      'Lodge',
      'Homestay',
      'Other',
    ],
    'Activities & Entertainment': [
      'Tours',
      'Museums',
      'Theme Parks',
      'Adventure Sports',
      'Water Sports',
      'Skiing',
      'Hiking',
      'Sightseeing',
      'Concerts/Shows',
      'Movies',
      'Events',
      'Attractions',
      'Excursions',
      'Guided Tours',
      'Entry Fees',    
      'Other',
    ],
    'Shopping': [
      'Souvenirs',
      'Clothing',
      'Electronics',
      'Local Products',
      'Duty Free',
      'Books',
      'Gifts',
      'Art & Crafts',
      'Jewelry',
      'Accessories',
      'Other',
    ],
    'Travel Essentials': [
      'Travel Insurance',
      'Visa Fees',
      'Passport/ID',
      'Travel Documents',
      'SIM Card',
      'Travel Adapter',
      'Luggage',
      'Travel Gear',
      'Other',
    ],
    'Health & Medical': [
      'Pharmacy',
      'Medication',
      'Doctor Visit',
      'Medical Insurance',
      'First Aid',
      'Vaccinations',
      'Health Check',
      'Travel Insurance',
      'Other',
    ],
    'Communication': [
      'Phone/Data',
      'WiFi',
      'Internet',
      'Roaming',
      'SIM Card',
      'Other',
    ],
    'Tips & Gratuities': [
      'Hotel Staff',
      'Restaurant',
      'Tour Guide',
      'Driver',
      'Porter',
      'Housekeeping',
      'Other',
    ],
    'Banking & Fees': [
      'ATM Fees',
      'Currency Exchange',
      'Bank Charges',
      'Transaction Fees',
      'Credit Card Fees',
      'Other',
    ],
    'Personal Care': [
      'Haircut',
      'Spa/Massage',
      'Salon',
      'Toiletries',
      'Laundry',
      'Dry Cleaning',
      'Other',
    ],
    'Miscellaneous': [
      'Lost & Found',
      'Emergency',
      'Storage',
      'Locker',
      'Other',
    ],
    'Prostitution': [
      'Prostitutes',
      'Strip Clubs',
      'Sex Workers',
      'Other',
    ],
  };

  static List<String> get categoryList => categories.keys.toList();

  static List<String> getSubcategories(String category) {
    return categories[category] ?? ['Other'];
  }
}

